---
title: "plots"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load packages
library(tidyverse)
library(ggdist)
library(patchwork)
library(kableExtra)
library(scales)
library(ggpubr)
library(data.table)
```

#LOAD VOX DATA
## Original Data - minDCF
```{r load-vox, echo=FALSE, results=FALSE}
output_data =read_csv('output_vox.csv') %>%
  mutate(confusion = str_extract_all(mindcf_confusion,'[0-9]+')) %>%
  unnest_wider(confusion) %>%
  mutate(TA=as.numeric(...1), FR=as.numeric(...2), FA=as.numeric(...3), TR=as.numeric(...4)) %>%
  select(-contains('eer'),-mindcf_confusion,-...1,-...2,-...3,-...4) %>%
  rename(train=num_train,test=num_test,n=num_overlap) %>%
  mutate(comparisons=train*test) %>%
  mutate(far=(FA/comparisons)) #%>%
  #mutate(comparisons=format(comparisons, scientific=FALSE, big.mark=","))

#separate into experiments
train_1 <- output_data %>%
    filter(experiment %in% c('train-2-1')) %>%
    mutate(x1 = train)
test_1 <- output_data %>%
    filter(experiment %in% c('test-1')) %>%
    mutate(x1 = test)
compare_1 <- output_data %>%
    filter(experiment == "train-2-1" | experiment == "test-1") %>%
    mutate(x1 = comparisons) #%>% 
    #filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000)
full_train <- output_data %>%
    filter(experiment %in% c('full-train-1')) %>%
    mutate(x1 = train)
full_test <- output_data %>%
    filter(experiment %in% c('full-test-1')) %>%
    mutate(x1 = test)
full_compare <- output_data %>%
    filter(experiment == "full-train-1" | experiment == "full-test-1") %>%
    mutate(x1 = comparisons)#%>%
    #filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000)
train_vtest <- output_data %>%
    filter(experiment %in% c('train-1-orig')) %>%
    mutate(x1 = train)

```

## Rank 1 Data - minDCF
```{r rank1-mindcf}
dirs <- c("outputs/train2/7205","outputs/train2/4000","outputs/train2/1000", "outputs/test/150", "outputs/test/500", "outputs/test/1000")

pat <-  "rank1_counts_mindcf.csv"
dat <- "r1"
for (i in 1:length(dirs)) {
  wd <- dirs[i]
  files <- list.files(path=wd, pattern=pat, full.names=TRUE) 
  
    for (j in 1:length(files)) {
      temp <- read.csv(files[j])
      temp$output_data <- str_sub(temp$files, 25, -1) 
      temp <- temp %>% select(output_data, FA, TA)
      v_name <- paste0(dat,"_", basename(wd),"_",basename(dirname(wd)))
      assign(v_name, temp)
    }
}

#r1_1000_train <- read.csv('outputs/train2/1000/rank1_counts.csv')
#r1_1000_train_orig <- read.csv('outputs/train2/1000/rank1_counts_orig.csv')# %>% merge(r1_1000_train2, by="output_data")
#r1 <- r1_1000_train %>% merge(r1_1000_train_orig, by="files")

r1_1000_test$train <- 6000
r1_1000_test$test <- 1000
r1_500_test$train <- 6000
r1_500_test$test <- 500
r1_150_test$train <- 6000
r1_150_test$test <- 150

r1_1000_train2$train <- 1000
r1_1000_train2$test <- 163
r1_4000_train2$train <- 4000
r1_4000_train2$test <- 163
r1_7205_train2$train <- 7205
r1_7205_train2$test <- 163

df_list <- list(r1_1000_test,r1_500_test,r1_150_test,r1_7205_train2, r1_4000_train2,r1_1000_train2)
r1_mindcf_counts <- rbindlist(df_list) %>% mutate(comparisons=train*test) %>%
  mutate(far=(FA/comparisons)) %>% mutate(x1 = comparisons) %>% mutate(precision = TA/(TA+FA)) %>% filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000) %>% rename(rank1_TA=TA, rank1_FA=FA)
#compare2 <- compare_1 %>% merge(rank1_counts, by="output_data")
```

## Known Overlap Data - minDCF
```{r known-overlap}
dirs <- c("outputs/train2/7205","outputs/train2/4000","outputs/train2/1000", "outputs/test/150", "outputs/test/500", "outputs/test/1000")

pat <-  "5_known_overlap_counts_mindcf.csv"
dat <- "ko"
for (i in 1:length(dirs)) {
  wd <- dirs[i]
  files <- list.files(path=wd, pattern=pat, full.names=TRUE) 
  
    for (j in 1:length(files)) {
      temp <- read.csv(files[j])
      temp$output_data <- str_sub(temp$files, 25, -1) 
      temp <- temp %>% select(output_data, FA, TA)
      v_name <- paste0(dat,"_", basename(wd),"_",basename(dirname(wd)))
      assign(v_name, temp)
    }
}

#r1_1000_train <- read.csv('outputs/train2/1000/rank1_counts.csv')
#r1_1000_train_orig <- read.csv('outputs/train2/1000/rank1_counts_orig.csv')# %>% merge(r1_1000_train2, by="output_data")
#r1 <- r1_1000_train %>% merge(r1_1000_train_orig, by="files")

ko_1000_test$train <- 6000
ko_1000_test$test <- 1000
ko_500_test$train <- 6000
ko_500_test$test <- 500
ko_150_test$train <- 6000
ko_150_test$test <- 150

ko_1000_train2$train <- 1000
ko_1000_train2$test <- 163
ko_4000_train2$train <- 4000
ko_4000_train2$test <- 163
ko_7205_train2$train <- 7205
ko_7205_train2$test <- 163

df_list <- list(ko_1000_test,ko_500_test,ko_150_test,ko_7205_train2, ko_4000_train2,ko_1000_train2)
ko_mindcf_counts <- rbindlist(df_list) %>% mutate(comparisons=train*test) %>%
  mutate(far=(FA/comparisons)) %>% mutate(x1 = comparisons) %>% mutate(precision = TA/(TA+FA)) %>% filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000)
```


#LOAD MAYO DATA
```{r load-mayo, echo=FALSE, results=FALSE}
output_data2 <-read_csv('output_mayo.csv') %>%
  mutate(confusion = str_extract_all(mindcf_confusion,'[0-9]+')) %>%
  unnest_wider(confusion) %>%
  mutate(TA=as.numeric(...1), FR=as.numeric(...2), FA=as.numeric(...3), TR=as.numeric(...4)) %>%
  select(-contains('eer'),-mindcf_confusion,-...1,-...2,-...3,-...4) %>%
  rename(train=num_train,test=num_test,n=num_overlap) %>%
  mutate(comparisons=train*test) %>%
  mutate(far=(FA/comparisons)) %>%
  mutate(mindcf_rank1_known_precision=as.numeric(mindcf_rank1_known_precision),
           mindcf_precision=as.numeric(mindcf_precision),
           mindcf_rank1_precision=as.numeric(mindcf_rank1_precision)) %>%
  mutate(mindcf_precision=ifelse(is.nan(mindcf_precision),0,mindcf_precision)) %>%
  mutate(mindcf_rank1_precision=ifelse(is.na(mindcf_rank1_precision),0,mindcf_rank1_precision)) %>%
  mutate(mindcf_rank1_precision=ifelse(is.na(mindcf_rank1_known_precision),0,mindcf_rank1_known_precision)) %>%
  mutate(far=ifelse(is.na(far),0,far))


task5_default <- output_data2 %>%
    filter(experiment %in% c("task-5-default")) %>% 
    mutate(test_type=factor(test_type, 
                            levels = c("s-physician",
                                       "grandfather",
                                       "w-*",
                                       "smr",
                                       "amr",
                                       "vowel"), 
                            labels = c("sentences",
                                       "reading",
                                       "word",
                                       "smr",
                                       "amr",
                                       "vowel")))

task5_pool_default <- output_data2 %>%
    filter(experiment %in% c("task-5-default","task-pool-default")) %>% 
    mutate(test_type=factor(test_type, 
                            levels = c("vowel, s-physician, w-*, amr-*, smr-*, grandfather",
                                       "s-physician",
                                       "grandfather",
                                       "w-*",
                                       "smr",
                                       "amr",
                                       "vowel"), 
                            labels = c("pool",
                                       "sentences",
                                       "reading",
                                       "word",
                                       "smr",
                                       "amr",
                                       "vowel")))

task5_within <- output_data2 %>%
    filter(experiment %in% c("task-5-default-within")) %>% 
    mutate(test_type=factor(test_type, 
                            levels = c("s-physician",
                                       "grandfather",
                                       "w-*",
                                       "smr",
                                       "amr",
                                       "vowel"), 
                            labels = c("sentences",
                                       "reading",
                                       "word",
                                       "smr",
                                       "amr",
                                       "vowel")))
```


# VOXCELEB PLOTS
```{r colors}
# COLOR FRIENDLY RED AND GREEN
green_c <- "#009E73"
red_c <- "#D55E00"
```

```{r realistic-acceptances-mindcf, echo=FALSE}

# PLOT A - known set size, regular
# calculate Pearson's Coefficient
corr_train <- cor.test(train_1$x1, train_1$FA, method=c("pearson"))

# Plot TA/FA counts vs. number of known speakers
plot_a <- train_1 %>%
        select(x1, TA, FA) %>%
        pivot_longer(-x1) %>%
      ggplot(aes(x1, value, color=name))+
      geom_point(position=position_jitterdodge(jitter.width=800,jitter.height=0.1, dodge.width=1600),
               size=3,
               alpha=0.35, 
               shape=21)+
      #geom_abline(intercept=lm_total_coef[1], slope = lm_total_coef[2], alpha=0.4, linetype = "dashed")+
      geom_errorbarh(data = train_1 %>% select(x1,TA,FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-800,xmax=x1+800,group=name), stat=,position=position_dodge(width=1600),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(train_1$x1)) +
    scale_color_manual(values=c(red_c,green_c))+
    ylim(0,6) +
    labs(tag = substitute(paste(bold("(a)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+
    ylab("N")+xlab("# Known Speakers")+ggtitle("Known Set: Total Acceptances", subtitle = "strict minDCF threshold") 

# add Pearson's correlation information
plot_a <- plot_a + geom_text(x=-Inf, y=6, label='FA ~ known speakers', hjust=-.1, yjust=0, size=3, color="#000000",show.legend = FALSE) + geom_text(x=-Inf, y=5.7, label=paste0("r = ",as.character(signif(corr_train$estimate, digits=4))), hjust=-.2, yjust=0, size=3,show.legend = FALSE) + geom_text(x=-Inf, y=5.4, label=paste0("p-value = ", as.character(signif(corr_trainl$p.value, digits=5))), hjust=-.1, yjust=0, size=3,show.legend = FALSE)


# PLOT B - unknown set size, regular
# pearson's correlation coefficient
corr_test <- cor.test(test_1$x1, test_1$FA, method=c("pearson"))

# Plot FA/TA counts vs number of unknown speakers
plot_b <- test_1 %>%
        select(x1, TA, FA) %>%
        pivot_longer(-x1) %>%
      ggplot(aes(x1, value, color=name))+
      geom_point(position=position_jitterdodge(jitter.width=100,jitter.height=0.1, dodge.width=200),
               size=3,
               alpha=0.35, 
               shape=21)+
      #geom_abline(intercept=lm_total_coef[1], slope = lm_total_coef[2], alpha=0.4, linetype = "dashed")+
      geom_errorbarh(data = test_1 %>% select(x1,TA,FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-100,xmax=x1+100,group=name), stat=,position=position_dodge(width=200),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(test_1$x1)) +
    scale_color_manual(values=c(red_c,green_c))+
    ylim(0,6) +
    labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+
    ylab("N")+xlab("# Unknown Speakers")+ggtitle("Unknown Set: Total Acceptances", subtitle = "strict minDCF threshold") 

# add pearson's information
plot_b <- plot_b + geom_text(x=-Inf, y=6, label='FA ~ unknown speakers', hjust=-.1, yjust=0, size=3, color="#000000",show.legend = FALSE) + geom_text(x=-Inf, y=5.7, label=paste0("r = ",as.character(signif(corr_testl$estimate, digits=4))), hjust=-.2, yjust=0, size=3,show.legend = FALSE) + geom_text(x=-Inf, y=5.4, label=paste0("p-value = ", as.character(signif(corr_test$p.value, digits=4))), hjust=-.1, yjust=0, size=3,show.legend = FALSE)

# PLOT C - Search Space Size, regular
compare <- compare_1 %>% 
    filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000) 

#pearson's correlation coefficient
corr_total <- cor.test(compare$x1, compare$FA, method=c("pearson"))

#Plot FA/TAs vs total number of comparisons (known speakers * unknown speakers)
plot_c <- compare %>%
        select(x1, TA, FA) %>%
        pivot_longer(-x1) %>%
      ggplot(aes(x1, value, color=name))+
      geom_point(position=position_jitterdodge(jitter.width=425000,jitter.height=0.1, dodge.width=850000),
               size=3,
               alpha=0.35, 
               shape=21)+
      #geom_abline(intercept=lm_total_coef[1], slope = lm_total_coef[2], alpha=0.4, linetype = "dashed")+
      geom_errorbarh(data = compare %>% select(x1,TA,FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-425000,xmax=x1+425000,group=name), stat=,position=position_dodge(width=850000),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(compare$x1)) +
    scale_color_manual(values=c(red_c,green_c))+
    ylim(0,6) +
    labs(tag = substitute(paste(bold("(c)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "none", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic", ),plot.tag = element_text())+
    ylab("N")+xlab("# Comparisons")+ggtitle("Search Space: Total Acceptances", subtitle = "strict minDCF threshold") 
  
# add correlation information
  plot_c <- plot_c + geom_text(x=-Inf, y=6, label='FA ~ comparisons', hjust=-.1, yjust=0, size=3, color="#000000",show.legend = FALSE) + 
    geom_text(x=-Inf, y=5.7, label=paste0("r = ",as.character(signif(corr_total$estimate, digits=4))), hjust=-.2, yjust=0, size=3,show.legend = FALSE) + 
    geom_text(x=-Inf, y=5.4, label=paste0("p-value < 2.2e-16"), hjust=-.1, yjust=0, size=3, show.legend = FALSE)
  

# arrange plots  
t <- ggarrange(plot_a,plot_b,plot_c, ncol=2, nrow=2, common.legend = TRUE, legend="bottom")

# SAVE PLOTS
name1 <- paste0(paste('realistic','counts','mindcf', sep="_"),'.png')
  
  #p1 <- (plots[[1]] + plots[[2]])
ggsave(filename=name1,plot=t, width=10,height=10)
```

```{r realistic-rates}
# PLOT A - regular precision
compare <- compare_1 %>% 
    filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000)
plot_a <- compare %>%
    select(x1, mindcf_precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=350000),
               size=3,
               alpha=0.35, 
               shape=21)+
  geom_errorbarh(data = compare %>% select(x1,mindcf_precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), stat=,position=position_dodge(width=700000),height=0,size=2)+
    scale_x_continuous(labels = comma,breaks = unique(compare$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  theme_classic() +
  labs(tag = substitute(paste(bold("(a)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+
  ylab("Precision: TA/(TA+FA)")+xlab("# Comparisons")+ggtitle("Precision", subtitle = "strict minDCF threshold")

#Plot C - FAR
plot_b <- compare %>%
    select(x1, far) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=350000),
               size=3,
               alpha=0.35, 
               shape=21)+
  #geom_hline(yintercept=compare$far%>%na.omit()%>%mean(),linetype=2) +
  geom_errorbarh(data = compare %>% select(x1,far)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), stat=,position=position_dodge(width=700000),height=0,size=2)+
  theme_classic() +
  scale_x_continuous(labels = comma,breaks = unique(compare$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("FAR: FA/Total Attempts")+xlab("# Comparisons")+ggtitle("False Acceptance Rate (FAR)", subtitle = "strict minDCF threshold")

#arrange plots
t <- ggarrange(plot_a, plot_b,ncol=2, nrow=1)

#SAVE PLOTS
name1 <- paste0(paste('realistic','rates','mindcf', sep="_"),'.png')
ggsave(filename=name1,plot=t, width=10,height=5)
```

```{r worstcase-plots}
# KNOWN OVERLAP - SEARCH SPACE
# pearson's correlation
corr_known <- cor.test(ko_mindcf_counts$x1, ko_mindcf_counts$FA, method=c("pearson"))

# plot FA/TA counts for known overlap
plot_a <- ko_mindcf_counts %>%
    select(x1, TA, FA) %>%
        pivot_longer(-x1) %>%
      ggplot(aes(x1, value, color=name))+
      geom_point(position=position_jitterdodge(jitter.width=425000,jitter.height=0.1, dodge.width=850000),
               size=3,
               alpha=0.35, 
               shape=21)+
      #geom_abline(intercept=lm_known_coef[1], slope = lm_known_coef[2], alpha=0.4, linetype = "dashed")+
      geom_errorbarh(data = ko_mindcf_counts %>% select(x1,TA,FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-425000,xmax=x1+425000,group=name), stat=,position=position_dodge(width=850000),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(ko_mindcf_counts$x1)) +
    scale_color_manual(values=c(red_c,green_c))+
    ylim(0,5) +labs(tag = substitute(paste(bold("(a)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+
    ylab("N")+xlab("# Comparisons")+ggtitle("Known Overlap: Total Acceptances", subtitle = "strict minDCF threshold") 

#add correlation information
plot_a <- plot_a + geom_text(x=-Inf, y=5, label='FA ~ comparisons', hjust=-.1, yjust=0, size=3, color="#000000", show.legend = FALSE) + geom_text(x=-Inf, y=4.75, label=paste0("r = ",as.character(signif(corr_known$estimate, digits=4))), hjust=-.2, yjust=0, size=3, show.legend = FALSE) + geom_text(x=-Inf, y=4.5, label=paste0("p-value < 2.2e-16"), hjust=-.1, yjust=0, size=3, show.legend = FALSE)

# KNOWN OVERLAP - PRECISION
plot_b <- ko_mindcf_counts %>%
    select(x1, precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=350000),
               size=3,
               alpha=0.35, 
               shape=21)+
  geom_errorbarh(data = ko_mindcf_counts %>% select(x1,precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), stat=,position=position_dodge(width=700000),height=0,size=2)+
  theme_classic() +
  scale_x_continuous(labels = comma,breaks = unique(ko_mindcf_counts$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("Precision: TA/(TA+FA)")+xlab("# Comparisons")+ggtitle("Known Overlap: Precision", subtitle = "strict minDCF threshold")

#PLOT C - full overlap false acceptances
full_compare <- full_compare %>% filter(x1==163000 | x1==1174415 | x1==3000000 | x1==6000000)
corr_full <- cor.test(full_compare$x1, full_compare$FA, method=c("pearson"))

plot_c <- full_compare %>%
        select(x1, FA) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position='jitter',
               size=3,
               alpha=0.35, 
               shape=21,
               color=red_c)+
  geom_errorbarh(data = full_compare %>% select(x1,FA)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), color=red_c,stat=,position=position_dodge(width=700000),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(full_compare$x1)) +
  labs(tag = substitute(paste(bold("(c)")))) +
    ylim(0,8) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("N")+xlab("# Comparisons")+ggtitle("Full Overlap: Total False Acceptances", subtitle = "strict minDCF threshold")

plot_c <- plot_c + geom_text(x=-Inf, y=8, label='FA ~ comparisons', hjust=-.1, yjust=0, size=3, color="#000000") + geom_text(x=-Inf, y=7.6, label=paste0("r = ",as.character(signif(corr_full$estimate, digits=4))), hjust=-.2, yjust=0, size=3, color=red_c) + geom_text(x=-Inf, y=7.2, label=paste0("p-value = ", as.character(signif(corr_full$p.value, digits=4))), hjust=-.1, yjust=0, size=3, color=red_c)


# Plot D full overlap true acceptances
plot_d <- full_compare %>%
    select(x1, TA) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position='jitter',
               size=3,
               alpha=0.35, 
               shape=21,
               color=green_c)+
  geom_errorbarh(data = full_compare %>% select(x1,TA)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), color=green_c, stat=,position=position_dodge(width=700000),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(full_compare$x1)) +
  labs(tag = substitute(paste(bold("(d)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("N")+xlab("# Comparisons")+ggtitle("Full Overlap: Total True Acceptances", subtitle = "strict minDCF threshold")

plot_e <- full_compare %>%
    select(x1, mindcf_precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=350000),
               size=3,
               alpha=0.35, 
               shape=21)+
  geom_errorbarh(data = full_compare %>% select(x1,mindcf_precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), stat=,position=position_dodge(width=700000),height=0,size=2)+
  theme_classic() +
  scale_x_continuous(labels = comma,breaks = unique(full_compare$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(e)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("Precision: TA/(TA+FA)")+xlab("# Comparisons")+ggtitle("Full Overlap: Precision", subtitle = "strict minDCF threshold")

# arrange plots
t <- ggarrange(plot_a,plot_b,plot_c,plot_d, ncol=2, nrow=2, common.legend = TRUE, legend="bottom")

# SAVE PLOTS
name1 <- paste0(paste('limited_overlap','counts','mindcf', sep="_"),'.png')
  
  #p1 <- (plots[[1]] + plots[[2]])
ggsave(filename=name1,plot=t, width=10,height=10)

```

```{r far-summary}
# get summary of false acceptance rate across # of speakers
far.summary <- function(compare){
  far.sum <- compare %>% select(x1,far)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value))
  far.mean <- compare$far%>%na.omit()%>%mean()
  far.sum$all_mean <- far.mean
  return (far.sum)
}

comparisons_far <- far.summary(compare)
#known_far <- far.summary(ko_mindcf_counts)
#full_far <- far.summary(full_compare)
```

```{r rank1-plots}
# PLOT D - Search Space Size, rank 1
  
 # corr_known <- cor.test(r1_mindcf_counts$x1, r1_mindcf_counts$rank1_FA, method=c("pearson"))
  
#  plot_d <- r1_mindcf_counts %>%
#        select(x1, rank1_TA, rank1_FA) %>%
#        pivot_longer(-x1) %>%
#      ggplot(aes(x1, value, color=name))+
#      geom_point(position=position_jitterdodge(jitter.width=425000,jitter.height=0.1, dodge.width=850000),
#               size=3,
#               alpha=0.35, 
#               shape=21)+
#      #geom_abline(intercept=lm_total_coef[1], slope = lm_total_coef[2], alpha=0.4, linetype = "dashed")+
#      geom_errorbarh(data = r1_mindcf_counts %>% select(x1,rank1_TA,rank1_FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-425000,xmax=x1+425000,group=name), stat=,position=position_dodge(width=850000),height=0,size=2)+
#        theme_classic()+
#    scale_x_continuous(labels = comma,breaks = unique(r1_mindcf_counts$x1)) +
##    scale_color_manual(values=c(red_c,green_c))+
##    ylim(0,6) +
#    labs(tag = "(d)") +
#  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "none", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic", colour = "gray"),plot.tag = element_text())+
 #   ylab("N")+xlab("Search Space Size (# Comparisons)")+ggtitle("Search Space: Rank 1 Acceptances", subtitle = "strict minDCF threshold") 
  
#  plot_d <- plot_d + geom_text(x=-Inf, y=6, label='FA ~ comparisons', hjust=-.1, yjust=0, size=3, color="#000000") + geom_text(x=-Inf, y=5.7, label=paste0("r = ",as.character(signif(corr_known$estimate, digits=4))), hjust=-.2, yjust=0, size=3) + geom_text(x=-Inf, y=5.4, label=paste0("p-value < 2.2e-16"), hjust=-.1, yjust=0, size=3)
#PLOT B - rank 1 precision
plot_b <- r1_mindcf_counts %>%
    select(x1, precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=350000),
               size=3,
               alpha=0.35, 
               shape=21)+
  geom_errorbarh(data = r1_mindcf_counts %>% select(x1,precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-350000,xmax=x1+350000), stat=,position=position_dodge(width=700000),height=0,size=2)+
  theme_classic() +
  scale_x_continuous(labels = comma,breaks = unique(r1_mindcf_counts$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic", colour = "gray"),plot.tag = element_text())+ylab("Precision: TA/(TA+FA)")+xlab("Search Space Size (# Comparisons)")+ggtitle("Rank 1 Precision", subtitle = "strict minDCF threshold")
```


# MAYO PLOTS
```{r mayo-summary}
# summarize mayo results
mayo.summary <- function(mayo){
  count.sum <- mayo %>% select(test_type,TA,FA) %>% pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%group_by(test_type,name)%>%summarize(value=mean(value))
  count.known <- mayo %>% select(test_type,TA,FA,n,mindcf_rank1_known_precision) %>% # make it like exp_three
    mutate(TotPos=TA+FA) %>% 
    mutate(TA=pmin(TotPos,n)*mindcf_rank1_known_precision, # the max number of positives to consider would be 5, but it may be lower
           FA=pmin(TotPos,n)-TA) %>% na.omit() %>% select(test_type,TA,FA) %>% pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%group_by(test_type,name)%>%summarize(value=mean(value))
  count.sum$known <- count.known$value
  return (count.sum)
}

summary.tpa <- mayo.summary(task5_pool_default)
sum.tpa.ta <- summary.tpa %>% filter(name=='TA')
sum.tpa.fa <- summary.tpa %>% filter(name=='FA')
sum.tpa <- sum.tpa.ta %>% merge(sum.tpa.fa, by="test_type") %>% mutate(proportion = value.x/value.y)

summaray.tw <-mayo.summary(task5_within)
sum.tw.ta <- summary.tw %>% filter(name=='TA')
sum.tw.fa <- summary.tw %>% filter(name=='FA')
sum.tw <- sum.tw.ta %>% merge(sum.tw.fa, by="test_type") %>% mutate(proportion = value.x/value.y)

```

```{r mayo-plots}
## ACROSS TASK counts - with pooling
pool <- TRUE
plot_a <- task5_pool_default %>% select(test_type,TA,FA) %>%
    pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%
    ggplot(aes(x = test_type, y=value,color=name)) + scale_x_discrete(drop=FALSE)+
    geom_point(size=2,
               position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0.1, dodge.width = 0.6),
               alpha=0.35, 
               shape=21,
               show.legend = F) +
 geom_errorbar(data = task5_pool_default %>% select(test_type,TA,FA) %>% pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%group_by(test_type,name)%>%summarize(value=mean(value)), aes(ymin=..y..,ymax=..y..), position=position_dodge(0.6),width=0.6,size=2)+
    theme_classic()+ 
    scale_color_manual(values=c(red_c,green_c))+
  ylim(0,30)+
    labs(tag = substitute(paste(bold("(a)")))) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.position = "bottom", legend.title = element_blank(),plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic", ), axis.title.x = element_blank(),plot.tag = element_text())+ylab("N")+ggtitle("Cross-task: Total Acceptances", subtitle = "default minDCF threshold")
  if(pool) {plot_a <- plot_a + annotate("rect", xmin = 0.5, xmax = 0 + 1.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=0.6, y=Inf, label=c("Pooling"), size=5, alpha=0.3, hjust=1.1)+
    annotate("rect", xmin = 1.5, xmax = 2.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=1.6, y=Inf, label=c("Baseline"), size=5, alpha=0.3, hjust=1.1)} else if (across) {plot_a <- plot_a + annotate("rect", xmin = 0.5, xmax = 0 + 1.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=0.6, y=Inf, label=c("Baseline"), size=5, alpha=0.3, hjust=1.1)}

### Across-task PRECISION
plot_b <- task5_pool_default %>% mutate(x1=test_type)%>%
    select(x1, mindcf_precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(size=2,
               position = 'jitter',
               alpha=0.35, 
               shape=21,
               show.legend = F) +
  geom_errorbar(data = task5_pool_default %>% mutate(x1=test_type)%>% select(x1,mindcf_precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(ymin=..y.., ymax=..y..), width=0.6, size=2)+
  theme_classic() +
  labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),axis.title.x = element_blank(),plot.tag = element_text())+ylab("Precision: TA/(TA+FA)")+ggtitle("Cross-task: Precision", subtitle = "default minDCF threshold")
  if(pool) {plot_b <- plot_b + annotate("rect", xmin = 0.5, xmax = 0 + 1.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=0.6, y=Inf, label=c("Pooling"), size=5, alpha=0.3, hjust=1.1)+
    annotate("rect", xmin = 1.5, xmax = 2.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=1.6, y=Inf, label=c("Baseline"), size=5, alpha=0.3, hjust=1.1)} else if (across) {plot_a <- plot_a + annotate("rect", xmin = 0.5, xmax = 0 + 1.5, ymin = -Inf, ymax = Inf, alpha=0.2, fill="gray50")+
    annotate("text", angle=90, x=0.6, y=Inf, label=c("Baseline"), size=5, alpha=0.3, hjust=1.1)}

## WITHIN-TASK counts
plot_c <- task5_within %>% select(test_type,TA,FA) %>%
    pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%
    ggplot(aes(x = test_type, y=value,color=name)) + scale_x_discrete(drop=FALSE)+
    geom_point(size=2,
               position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0.1, dodge.width = 0.6),
               alpha=0.35, 
               shape=21,
               show.legend = F) +
 geom_errorbar(data = task5_within %>% select(test_type,TA,FA) %>% pivot_longer(cols = c(TA,FA)) %>%
    select(test_type,name,value) %>%group_by(test_type,name)%>%summarize(value=mean(value)), aes(ymin=..y..,ymax=..y..), position=position_dodge(0.6),width=0.6,size=2)+
    theme_classic()+ 
    scale_color_manual(values=c(red_c,green_c))+
  ylim(0,30)+
    labs(tag = substitute(paste(bold("(c)")))) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.position = "bottom", legend.title = element_blank(),plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"), axis.title.x = element_blank(),plot.tag = element_text())+ylab("N")+ggtitle("Within-task: Total Acceptances", subtitle = "default minDCF threshold")


### WITHIN-TASK PRECISION 
plot_d <- task5_within %>% mutate(x1=test_type)%>%
    select(x1, mindcf_precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(size=2,
               position = 'jitter',
               alpha=0.35, 
               shape=21,
               show.legend = F) +
  geom_errorbar(data = task5_within %>% mutate(x1=test_type)%>% select(x1,mindcf_precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(ymin=..y.., ymax=..y..), width=0.6, size=2)+
  theme_classic() +
  labs(tag = substitute(paste(bold("(d)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),axis.title.x = element_blank(), plot.tag = element_text())+ylab("Precision: TA/(TA+FA)")+ggtitle("Within-task: Precision", subtitle = "default minDCF threshold")

#arrange
t <- ggarrange(plot_a,plot_b,plot_c,plot_d, ncol=2, nrow=2,common.legend = TRUE, legend="bottom")

#SAVE PLOTS 
name1 <- paste0(paste('mayo','counts', sep="_"),'.png')
ggsave(filename=name1,plot=t, width=10,height=10)
```

# NON-OVERLAP
## Determine how many FA are due to non-overlapping speakers in our realistic scenario
```{r non-overlap}
dirs <- c("outputs/train2/7205","outputs/train2/4000","outputs/train2/1000", "outputs/test/150", "outputs/test/500", "outputs/test/1000")

pat <-  "non_overlap_acceptances.csv"
dat <- "noa"
for (i in 1:length(dirs)) {
  wd <- dirs[i]
  files <- list.files(path=wd, pattern=pat, full.names=TRUE) 
  
    for (j in 1:length(files)) {
      temp <- read.csv(files[j])
      temp$output_data <- str_sub(temp$files, 25, -1) 
      temp <- temp %>% select(output_data, non_o_true)
      v_name <- paste0(dat,"_", basename(wd),"_",basename(dirname(wd)))
      assign(v_name, temp)
    }
}

fa_7205 <- train_1 %>% filter(train == 7205) %>% select(output_data, FA) %>% merge(noa_7205_train2)
avg_non_o_7205 <- sum(fa_7205$non_o_true)/sum(fa_7205$FA)
fa_4000 <- train_1 %>% filter(train == 4000) %>% select(output_data, FA)  %>% merge(noa_4000_train2)
avg_non_o_4000 <- sum(fa_4000$non_o_true)/sum(fa_4000$FA)
fa_1000 <- train_1 %>% filter(train == 1000) %>% select(output_data, FA) %>% merge(noa_1000_train2)
avg_non_o_1000 <- sum(fa_1000$non_o_true)/sum(fa_1000$FA)
fa_150 <- test_1 %>% filter(test==150) %>% select(output_data, FA) %>% merge(noa_150_test)
avg_non_o_150 <- sum(fa_150$non_o_true)/sum(fa_150$FA)
fa_500 <- test_1 %>% filter(test==500) %>% select(output_data, FA) %>% merge(noa_500_test)
avg_non_o_500 <- sum(fa_500$non_o_true)/sum(fa_500$FA)
fa_1000_t <- test_1 %>% filter(test==1000) %>% select(output_data, FA) %>% merge(noa_1000_test)
avg_non_o_1000_t <- sum(fa_1000_t$non_o_true)/sum(fa_1000_t$FA)

non_overlap_fa <- data.frame(experiment = c("train_7205", "train_4000", "train_1000", "test_1000", "test_500", "test_150"), non_o_fa = c(avg_non_o_7205,avg_non_o_4000,avg_non_o_1000,avg_non_o_1000_t,avg_non_o_500,avg_non_o_150))

```

# VOX-TEST - SUPPLEMENTARY PLOTS
```{r vox-test-plots}
corr_suppl <- cor.test(train_vtest$x1, train_vtest$FA, method=c("pearson"))
#Total acceptances 
# PLOT A - known set size, regular
plot_a <- train_vtest %>%
        select(x1, TA, FA) %>%
        pivot_longer(-x1) %>%
      ggplot(aes(x1, value, color=name))+
      geom_point(position=position_jitterdodge(jitter.width=300,jitter.height=0.1, dodge.width=600),
               size=3,
               alpha=0.35, 
               shape=21)+
      #geom_abline(intercept=lm_total_coef[1], slope = lm_total_coef[2], alpha=0.4, linetype = "dashed")+
      geom_errorbarh(data = train_vtest %>% select(x1,TA,FA)%>% pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-300,xmax=x1+300,group=name), stat=,position=position_dodge(width=600),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(train_vtest$x1)) +
    scale_color_manual(values=c(red_c,green_c))+
    labs(tag = substitute(paste(bold("(a)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "left", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+
    ylab("N")+xlab("# Known Speakers")+ggtitle("Total Acceptances", subtitle = "strict minDCF threshold") 
plot_a <- plot_a + geom_text(x=-Inf, y=11, label='FA ~ # known speakers', hjust=-.1, yjust=0, size=3, color="#000000") + geom_text(x=-Inf, y=10.5, label=paste0("r = ",as.character(signif(corr_suppl$estimate, digits=4))), hjust=-.2, yjust=0, size=3, color=red_c) + geom_text(x=-Inf, y=10, label=paste0("p-value = ", as.character(signif(corr_suppl$p.value, digits=4))), hjust=-.1, yjust=0, size=3, color=red_c)

#precision
plot_b <- train_vtest %>%
    select(x1, mindcf_precision) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=300),
               size=3,
               alpha=0.35, 
               shape=21)+
  geom_errorbarh(data = train_vtest %>% select(x1,mindcf_precision)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-300,xmax=x1+300), stat=,position=position_dodge(width=600),height=0,size=2)+
        theme_classic()+
    scale_x_continuous(labels = comma,breaks = unique(train_vtest$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(b)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic", ),plot.tag = element_text())+
  ylab("Precision: TA/(TA+FA)")+xlab("# Known Speakers")+ggtitle("Precision", subtitle = "strict minDCF threshold")


# False acceptance rates
plot_c <- train_vtest %>%
    select(x1, far) %>%
  pivot_longer(-x1)%>%# make it like exp_three
  ggplot(aes(x=x1,y=value))+
         geom_point(position=position_jitter(width=300),
               size=3,
               alpha=0.35, 
               shape=21)+
  #geom_hline(yintercept=compare$far%>%na.omit()%>%mean(),linetype=2) +
  geom_errorbarh(data = train_vtest %>% select(x1,far)%>%na.omit()%>%pivot_longer(-x1)%>%group_by(x1,name)%>%summarise(value=mean(value)), aes(xmin=x1-300,xmax=x1+300), stat=,position=position_dodge(width=600),height=0,size=2)+
  theme_classic() +
  scale_x_continuous(labels = comma,breaks = unique(train_vtest$x1)) +
  scale_color_manual(values=c(red_c,green_c))+
  labs(tag = substitute(paste(bold("(c)")))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),legend.title = element_blank(),legend.position = "bottom", plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5, face = "italic"),plot.tag = element_text())+ylab("FAR: FA/Total Attempts")+xlab("# Known Speakers")+ggtitle("False Acceptance Rate (FAR)", subtitle = "strict minDCF threshold")

t <- ggarrange(plot_a, plot_b, plot_c,ncol=3, nrow=1, common.legend = TRUE, legend="left")

name1 <- paste0(paste('vox-test','rates', sep="_"),'.png')
  
ggsave(filename=name1,plot=t, width=15,height=5)

vtest.sum <- far.summary(train_vtest)
```